CREATE SCHEMA IF NOT EXISTS SF.TRANSFORMED;

CREATE OR REPLACE TABLE SF.TRANSFORMED.EMPLOYEE_TRANSFORMED (
    EMP_ID INTEGER,
    FULL_NAME STRING,
    DEPT STRING,
    LOAD_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE PROCEDURE SF.TRANSFORMED.SP_TRANSFORM_EMPLOYEE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    
    INSERT INTO SF.TRANSFORMED.EMPLOYEE_TRANSFORMED (EMP_ID, FULL_NAME, DEPT, LOAD_TIMESTAMP)
    SELECT 
        ID,
        UPPER(NAME),
        DEPARTMENT,
        CURRENT_TIMESTAMP()
    FROM SF.REPO.EMPLOYEE;

    RETURN 'Employee data transformed and loaded successfully.';
END;
$$;
