CREATE OR REPLACE PROCEDURE SF.PI_INGEST.INSERT_FACT_PAYMENT()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO SF.PI_INGEST.FACT_PAYMENT
        (AMOUNT, CREATED_AT, CURRENCY, ORDER_SK, PAYMENT_DATE,
         PAYMENT_ID, PAYMENT_METHOD, PAYMENT_SK, PAYMENT_STATUS)
    VALUES
        (100, CURRENT_TIMESTAMP(), 'USD', 1, CURRENT_DATE(),
         'PAY_001', 'CARD', 101, 'SUCCESS'),

        (250, CURRENT_TIMESTAMP(), 'EUR', 2, CURRENT_DATE(),
         'PAY_002', 'UPI', 102, 'FAILED'),

        (175, CURRENT_TIMESTAMP(), 'INR', 3, CURRENT_DATE(),
         'PAY_003', 'NETBANKING', 103, 'PENDING');

    RETURN 'Rows inserted';
END;
$$;
