CREATE OR REPLACE PROCEDURE SF.PI_INGEST.INSERT_SAMPLE_ORDERS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO SF.PI_INGEST.RAW_ORDERS (LOAD_TS, ORDER_JSON, RAW_ORDER_ID)
        VALUES (
            CURRENT_TIMESTAMP(),
            OBJECT_CONSTRUCT('order_no', 12, 'amount', 12*10),
            'ORDER_' || 12
        );
END;
$$;
