-- filename: create_PI_INGEST_tables.sql
-- Snowflake-compatible DDL for a small data warehouse (star schema + SCD2 dims)

-- 1) create schema
CREATE OR REPLACE SCHEMA IF NOT EXISTS PI_INGEST;

-- 2) date dimension (static lookup)
CREATE OR REPLACE TABLE PI_INGEST.DIM_DATE (
  DATE_KEY        DATE PRIMARY KEY,
  YEAR            NUMBER(4,0),
  MONTH           NUMBER(2,0),
  DAY             NUMBER(2,0),
  DAY_OF_WEEK     VARCHAR(10),
  IS_BUSINESS_DAY BOOLEAN,
  CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3) SCD2 customer dimension (includes IS_ACTIVE, START_DATE, END_DATE)
CREATE OR REPLACE TABLE PI_INGEST.DIM_CUSTOMER (
  CUSTOMER_SK     NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,     -- surrogate key
  CUSTOMER_ID     NUMBER(10,0) NOT NULL,                      -- natural/business key
  FIRST_NAME      VARCHAR(100),
  LAST_NAME       VARCHAR(100),
  EMAIL           VARCHAR(255),
  PHONE           VARCHAR(50),
  ADDRESS_LINE1   VARCHAR(255),
  ADDRESS_LINE2   VARCHAR(255),
  CITY            VARCHAR(100),
  STATE           VARCHAR(100),
  POSTAL_CODE     VARCHAR(30),
  COUNTRY         VARCHAR(100),
  IS_ACTIVE       VARCHAR(1) DEFAULT 'Y',                     -- 'Y' or 'N'
  START_DATE      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),  -- when this record became effective
  END_DATE        TIMESTAMP_NTZ,                              -- null for current active record
  ROW_INSERTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Optional: create unique constraint on business key + version window (note: Snowflake does not enforce PK/UNIQUE strictly)
ALTER TABLE PI_INGEST.DIM_CUSTOMER ADD CONSTRAINT UQ_CUSTOMER_BUSINESSKEY UNIQUE (CUSTOMER_ID, START_DATE);

-- 4) SCD2 product dimension
CREATE OR REPLACE TABLE PI_INGEST.DIM_PRODUCT (
  PRODUCT_SK      NUMBER(10,0) AUTOINCREMENT PRIMARY KEY,
  PRODUCT_ID      VARCHAR(50) NOT NULL,
  PRODUCT_NAME    VARCHAR(255),
  PRODUCT_DESC    VARCHAR(2000),
  CATEGORY        VARCHAR(100),
  PRICE           NUMBER(12,2),
  IS_ACTIVE       VARCHAR(1) DEFAULT 'Y',
  START_DATE      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  END_DATE        TIMESTAMP_NTZ,
  ROW_INSERTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE PI_INGEST.DIM_PRODUCT ADD CONSTRAINT UQ_PRODUCT_BUSINESSKEY UNIQUE (PRODUCT_ID, START_DATE);

-- 5) staging / raw orders (optional raw capture)
CREATE OR REPLACE TABLE PI_INGEST.RAW_ORDERS (
  RAW_ORDER_ID    VARCHAR(100),
  ORDER_JSON      VARIANT,
  LOAD_TS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 6) fact order header
CREATE OR REPLACE TABLE PI_INGEST.FACT_ORDER (
  ORDER_SK        NUMBER(12,0) AUTOINCREMENT PRIMARY KEY,
  ORDER_ID        VARCHAR(50) NOT NULL,
  CUSTOMER_SK     NUMBER(10,0),            -- FK -> DIM_CUSTOMER (surrogate)
  ORDER_DATE      TIMESTAMP_NTZ,
  ORDER_STATUS    VARCHAR(50),
  TOTAL_AMOUNT    NUMBER(18,2),
  CURRENCY        VARCHAR(10),
  CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 7) order line items (fact detail)
CREATE OR REPLACE TABLE PI_INGEST.FACT_ORDER_ITEM (
  ORDER_ITEM_SK   NUMBER(12,0) AUTOINCREMENT PRIMARY KEY,
  ORDER_SK        NUMBER(12,0) NOT NULL,   -- FK -> FACT_ORDER.ORDER_SK
  PRODUCT_SK      NUMBER(10,0),            -- FK -> DIM_PRODUCT.PRODUCT_SK
  QUANTITY        NUMBER(10,2),
  UNIT_PRICE      NUMBER(18,4),
  LINE_TOTAL      NUMBER(18,4),
  CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 8) payments fact
CREATE OR REPLACE TABLE PI_INGEST.FACT_PAYMENT (
  PAYMENT_SK      NUMBER(12,0) AUTOINCREMENT PRIMARY KEY,
  PAYMENT_ID      VARCHAR(100),
  ORDER_SK        NUMBER(12,0),
  PAYMENT_DATE    TIMESTAMP_NTZ,
  PAYMENT_METHOD  VARCHAR(50),
  AMOUNT          NUMBER(18,2),
  CURRENCY        VARCHAR(10),
  PAYMENT_STATUS  VARCHAR(50),
  CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 9) example audit/log table for loads
CREATE OR REPLACE TABLE PI_INGEST.LOAD_AUDIT_LOG (
  AUDIT_ID        NUMBER(12,0) AUTOINCREMENT PRIMARY KEY,
  JOB_NAME        VARCHAR(200),
  SOURCE_NAME     VARCHAR(200),
  RECORDS_READ    NUMBER(18,0),
  RECORDS_INSERTED NUMBER(18,0),
  RECORDS_UPDATED NUMBER(18,0),
  RUN_STARTED_AT  TIMESTAMP_NTZ,
  RUN_ENDED_AT    TIMESTAMP_NTZ,
  STATUS          VARCHAR(50),
  MESSAGE         VARCHAR(2000)
);

-- End of file
