name: Python application

on:
  push:
    branches: ["main","dev"]
  pull_request:
    branches: ["main","dev"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Snowflake config file
      env:
        SNOWCLI_CONFIG: ${{ secrets.SNOWCLI_CONFIG }}
      run: |
        echo "$SNOWCLI_CONFIG" > config.toml
        chmod 600 config.toml
    - name: Install Snowflake CLI
      uses: Snowflake-Labs/snowflake-cli-action@v1.5
      with:
        cli-version: "latest"
        default-config-file-path: "config.toml"

    - name: Fetch latest commit into Snowflake Git Repository
      run: |
        snow sql -q "ALTER GIT REPOSITORY SNOW_CICD FETCH;" --connection demo
 
