name: Snowflake Auto Fetch

on:
  push:
   branches: [ "main","dev" ]
  pull_request:
   branches: [ "main","dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore private key
        run: |
          printf "%s" "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > rsa_key.p8
          chmod 600 rsa_key.p8

      - name: Create SnowCLI config file
        run: |
          cat <<EOF > config.toml
          [connections.default]
          account = "${{ secrets.SNOW_ACCOUNT }}"
          user = "${{ secrets.SNOW_USER }}"
          role = "${{ secrets.SNOW_ROLE }}"
          warehouse = "${{ secrets.SNOW_WAREHOUSE }}"
          private_key_path = "rsa_key.p8"
          authenticator = "SNOWFLAKE_JWT"
          database = "${{ secrets.SNOW_DATABASE }}"
          schema = "${{ secrets.SNOW_SCHEMA }}"
          EOF
          chmod 600 config.toml

      - uses: Snowflake-Labs/snowflake-cli-action@v1.5

      - name: Alter Snowflake Git Repo Fetch
        run: snow sql -q "ALTER GIT REPOSITORY <database>.<schema>.SNOW_CICD FETCH;"
 
